- hosts: mytomcat
  become: yes
  tasks:
  - name: i want to install apache2 server
    get_url:
      url: http://3.142.45.9:8082/artifactory/TestRepo/com/example/Login-/4.0/Login--4.0.war
      dest: /opt/tomcat/webapps/Login--4.0.war  
      force_basic_auth: yes
      url_username: admin
      url_password: Root@123