---
- hosts: 172.31.21.80
  become: yes
  tasks:
  - name: install java ubuntu
    apt:
      name: "{{myjavaonubuntu}}"
      state: present
    when: ansible_os_family == "Debian"
  - name: install java on RedHat
    yum:
     name: "{{myjavaonRedHat}}"
     state: present
    when: ansible_os_family=="RedHat"

