---
- hosts: mytomcat
  become: yes
  tasks:
  - name: i want to install apache2 server
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
  - name: i want to install software on RedHat