---
- hosts: 172.31.21.80
  become: yes
  tasks:
  - include_tasks: myfiles.yml
  - name: nstall web server
    apt:
      name: apache2
      state: present
  - name: start web server
    service:
     name: apache2
     state: started  
  - name: copy node server to node
    template:
     src: myindexfile.j2
     dest: /var/www/html/index.html 

