---
- hosts: all
  become: yes
  tasks:
  - name: i want to ping all
    ping:
  - name: i want to install apache
    apt:
      name: apache2
      state: present
  - name: Start service httpd, if not running
    service:
      name: apache2
      state: started
